PalmasMota/Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PalmasMota/Web/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio;
using Aplicacao;
using System.Configuration;
using System.Web.Security;

namespace Web.Controllers
{
    public class InicioController : Controller
    {
        private OperadorAplicacao operador;
        private SupervisorAplicacao supervisor;
        private FuncionarioAplicacao funcionario;
        private AutenticacaoADAplicacao autenticacao;

        public InicioController()
        {
            operador = new OperadorAplicacao();
            supervisor = new SupervisorAplicacao();
            funcionario = new FuncionarioAplicacao("bancoFrequencia");
            autenticacao = new AutenticacaoADAplicacao();
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string login, string senha)
        {
            try
            {
                string AD = "";
                AppSettingsReader reader = new AppSettingsReader();
                AD = (string)reader.GetValue("ACTIVE_DIRECTORY", typeof(string));
                var isValido = autenticacao.ValidarLogin(login, senha, AD);

                if (isValido)
                {
                    FormsAuthentication.SetAuthCookie(login, false);
                    Session["Usuario"] = login;
                    string dominio = (string)reader.GetValue("DOMINIO_ALIAS", typeof(string));
                    string bancoFrequencia = (string)reader.GetValue("BANCO_FREQUENCIA", typeof(string));

                    var pesquisa = autenticacao.isPesquisaValida(login, bancoFrequencia);

                    if (pesquisa)
                    {
                        ViewBag.Mensagem = "Usuário já preencheu o questionário";
                    }

                    var funcionarioDado = autenticacao.ObterDadosFuncionario(login, dominio, AD);//tipo funcionario qd dá ponto pega qq coisa dele

                    //Funcionario func = new Funcionario();
                    //var f = funcionario.ObterPesquisa(func);//qd é do tipo pega qq coisa dele

                    //foreach (var item in f)
                    //{
                    //    if (item.Funcao)
                    //    {
                            
                    //    }
                          
                    //}

                    if (funcionarioDado != null && funcionarioDado.Funcao.ToUpper().Contains("OPERADOR"))
                    {
                        return RedirectToAction("Cadastrar","Operador");
                    }
                    else
                    {
                        return RedirectToAction("Cadastrar","Supervisor");
                    }
                }
            }
            catch (Exception ex)
            {

                ViewBag.Mensagem = ex.Message;//pode ser uma msg no viewbag
            }
            return View();
        }
    }
}

PalmasMota/Web/Controllers/OperadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio;
using Aplicacao;

namespace Web.Controllers
{
    public class OperadorController : Controller
    {
        private OperadorAplicacao aplicacao;

        public OperadorController()
        {
            aplicacao = new OperadorAplicacao();
        }
        public ActionResult Sucesso()
        {
            return View();
        }

        public ActionResult Cadastrar()
        {
            //if (Session["Usuario"] == null)
            //{
            //    return RedirectToAction("Index","Home");
            //}
            //else
            //{
                return View();
            //}          
        }

        [HttpPost]
        public ActionResult Cadastrar(Operador operador)
        {
            
            if (ModelState.IsValid)
            {
                operador.LoginRede = "rodrigo.mota";
                    //Session["Usuario"].ToString();
                aplicacao.Salvar(operador);
                return RedirectToAction("Sucesso");
            }
            else
            {
                return View(operador);
            }  
        }
    }
}

PalmasMota/Web/Controllers/SupervisorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio;
using Aplicacao;


namespace Web.Controllers
{
    public class SupervisorController : Controller
    {
        private SupervisorAplicacao aplicacao;

        public SupervisorController()
        {
            aplicacao = new SupervisorAplicacao();
        }
        public ActionResult Sucesso()
        {
            return View();
        }

        public ActionResult Cadastrar()
        {
            if (Session["Usuario"] == null)
            {
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View();
            }     
        }

        [HttpPost]
        public ActionResult Cadastrar(Supervisor supervisor)
        {
            if (ModelState.IsValid)
            {
                supervisor.LoginRede = Session["Usuario"].ToString();
                aplicacao.Salvar(supervisor);
                return RedirectToAction("Sucesso");
            }
            else
            {
                return View(supervisor);
            }
            
        }
    }
}

PalmasMota/Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PalmasMota/Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PalmasMota/Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PalmasMota/Web/Views/Inicio/Index.cshtml
@{
    Layout = null;
    ViewBag.Title = "Avaliacao Palmas";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/bootstrap")
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 370px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }

            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }

            .form-signin input[type="text"],
            .form-signin input[type="password"] {
                font-size: 16px;
                height: auto;
                margin-bottom: 15px;
                padding: 7px 9px;
            }
    </style>
</head>
<body>
    <form class="form-signin" method="POST">
        <div align="center">
            <img src="~/Imagens/logo.png" />
        </div>

        <h2 class="form-signin-heading">Avaliação de Satisfação - Palmas</h2>

        @if (@ViewBag.Mensagem != null)
        {
            <div class="alert-error ">
                <span style="color: #CC0000;">@ViewBag.Mensagem </span>
            </div>
        }

        <input type="text" class="input-block-level" placeholder="Usuário" name="login" id="login">
        <input type="password" class="input-block-level" placeholder="Senha" name="senha" id="senha">

        <button class="btn btn-large btn-primary" type="submit">Acessar</button>

    </form>
</body>
</html>

PalmasMota/Web/Views/Operador/Cadastrar.cshtml
@model Dominio.Operador

@{
    //Layout = null;
    ViewBag.Title = "Cadastrar";
}

<div align="center">
    <h2>Questionário de Operador</h2>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" align="left">
        @*<h4>Operador</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
         1. Como você avalia a Supervisão quanto ao desenvolvimento da equipe?    
        <div class="col-md-10">
        <p></p>
        @Html.RadioButtonFor(x => x.Resposta1, "Ótimo")&nbsp Ótimo<br />    
        @Html.RadioButton("Resposta1", "Bom")&nbsp Bom<br />
        @Html.RadioButtonFor(x => x.Resposta1, "Regular")&nbsp Regular<br />
        @Html.RadioButtonFor(x => x.Resposta1, "Ruim")&nbsp Ruim<br />
            @*, new { htmlAttributes = new { @class = "form-control" } })*@  
        @Html.ValidationMessageFor(model => model.Resposta1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            2. Como você avalia o auxilio da Supervisão para o seu desenvolvimento?
        <div class="col-md-10">
            <p></p>
         @Html.RadioButtonFor(x => x.Resposta2, "Ótimo")&nbsp Ótimo<br/>
         @Html.RadioButton("Resposta2", "Bom")&nbsp Bom<br />
         @Html.RadioButtonFor(x => x.Resposta2, "Regular")&nbsp Regular<br />
         @Html.RadioButtonFor(x => x.Resposta2, "Ruim")&nbsp Ruim<br /> 
         @Html.ValidationMessageFor(model => model.Resposta2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            3. Como você avalia o treinamento e reuniões realizadas pela equipe de Desenvolvimento?
            <div class="col-md-10"> 
                <p></p>
                @Html.RadioButtonFor(x => x.Resposta3, "Ótimo")&nbsp Ótimo<br />
                @Html.RadioButton("Resposta3", "Bom")&nbsp Bom<br />
                @Html.RadioButtonFor(x => x.Resposta3, "Regular")&nbsp Regular<br />
                @Html.RadioButtonFor(x => x.Resposta3, "Ruim")&nbsp Ruim<br />
                @Html.ValidationMessageFor(model => model.Resposta3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            4. De que forma você aplica os conhecimentos transmitidos pelos supervisores na sua rotina de trabalho?
         <div class="col-md-10">
             <p></p>
                @Html.RadioButtonFor(x => x.Resposta4, "Total")&nbsp Ótimo<br />
                @Html.RadioButton("Resposta4", "Parcial")&nbsp Parcial<br />
                @Html.RadioButtonFor(x => x.Resposta4, "Não Aplico")&nbsp Não Aplico<br />
                @Html.RadioButtonFor(x => x.Resposta4, "Meu Supervisor não me desenvolve")&nbsp Meu Supervisor não me desenvolve<br />
                @Html.ValidationMessageFor(model => model.Resposta4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            5. Quais os resultados positivos que você espera conquistar através do acompanhamento de seu Supervisor?
            <div class="col-md-10">
                <p></p>
                @Html.RadioButtonFor(x => x.Resposta5, "Desenvolver mais conhecimento sobre o negócio")&nbsp Desenvolver mais conhecimento sobre o negócio<br />
                @Html.RadioButton("Resposta5", "Ganhar mais campanhas")&nbsp Ganhar mais campanhas<br />
                @Html.RadioButtonFor(x => x.Resposta5, "Alcançar melhores resultados")&nbsp Alcançar melhores resultados<br />
                @Html.RadioButtonFor(x => x.Resposta5, "Meu Supervisor não me desenvolve")&nbsp Meu Supervisor não me desenvolve<br />
                @Html.RadioButtonFor(x => x.Resposta5, "Desenvolver um atendimento de excelência e aproveitar as oportunidades de crescimento")&nbsp Desenvolver um atendimento de excelência e aproveitar as oportunidades de crescimento<br />
                @Html.ValidationMessageFor(model => model.Resposta5, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DataPesquisa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataPesquisa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataPesquisa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoginRede, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginRede, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoginRede, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <br />
        <div align="left">
            <input type="submit" value="Salvar" />
        </div>

    </div>
}
@*<div class="form-group" align="left">
    <div class="col-md-offset-2 col-md-10" align="left">
        <input type="submit" value="Salvar" class="btn btn-default" />
    </div>
</div>*@
@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

PalmasMota/Web/Views/Operador/Sucesso.cshtml
@{
    ViewBag.Title = "Sucesso";
}

<h2>Pesquisa Realizada com Sucesso!</h2>

@Html.ActionLink("Página Inicial","Index", "Inicio")

PalmasMota/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Operador", "Cadastrar", "Operador")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>